/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import factory.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import javax.swing.JOptionPane;
import factory.CalcSaida;
import java.sql.Statement;
import gui.TelaPrincipal;
/**
 *
 * @author kaiov
 */
public class Saida_carros extends javax.swing.JFrame {

    /**
     * Creates new form Saida_carros
     */
    public Saida_carros() {
        initComponents();
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSaida = new javax.swing.JButton();
        setDataS = new javax.swing.JTextField();
        setTempo = new javax.swing.JTextField();
        setValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        setId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        setHoraEntrada = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saida de Veiculos");

        jLabel1.setText("Data de Saida");

        jLabel2.setText("Tempo Estacionado");

        jLabel3.setText("Valor a ser pago");

        btnSaida.setText("Concluído");
        btnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidaActionPerformed(evt);
            }
        });

        setDataS.setEnabled(false);
        setDataS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDataSActionPerformed(evt);
            }
        });

        jLabel4.setText("ID");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Digite o Id do Carro para efetivar a Saida");

        jLabel6.setText("Hora de Entrada");

        setHoraEntrada.setEnabled(false);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSaida))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(setDataS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6))
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(setValor)
                                        .addComponent(setId)
                                        .addComponent(setTempo)
                                        .addComponent(setHoraEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(setId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(setHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(setTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(setValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setDataS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnSaida))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaActionPerformed
        // TODO add your handling code here:
       Connection con;
       PreparedStatement stmt;
       Statement st;
       String getId=setId.getText();
       String getHoraentrada=setHoraEntrada.getText();
       String getTempoestacionado=setValor.getText();
       
       
       
       
       try {
           
            
            con=new ConnectionFactory().getConnection();
            String sql = "select * from tbl_movimentacao where id = "+getId+"";
            stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            rs.next();
            if(getId.equals(rs.getString("id"))){
            String dataentrada=rs.getString("data_entrada");            
            String text=dataentrada.substring(0,8);
 
            
            setHoraEntrada.setText(text);
            con.close();
            
            
            }  
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Carro não Encontrado");
        }
       LocalDateTime agora = LocalDateTime.now();
            DateTimeFormatter formatterData = DateTimeFormatter.ofPattern("dd/MM/uuuu");
            String dataFormatada = formatterData.format(agora);
            DateTimeFormatter formatterHora = DateTimeFormatter.ofPattern("HH:mm:ss");
            String horasaida = formatterHora.format(agora);
            setDataS.setText(dataFormatada);
           
         
           String horario1=setHoraEntrada.getText();
           String horario2 = horasaida;
            LocalTime lt1 = LocalTime.parse(horario1);
            LocalTime lt2 = LocalTime.parse(horario2);
            long emHoras = lt1.until(lt2, ChronoUnit.HOURS);
            
            if (emHoras<0){
                emHoras= 24;
                setTempo.setText(emHoras+" "+"Horas");
            }
           
            
            if (emHoras<=9){
                
                setTempo.setText("0"+emHoras+" "+"Horas");
            }
            
            
            else{
                setTempo.setText(emHoras+" "+"Horas");
            }
           
           
            
            
            String f=setTempo.getText();
            String text=f.substring(0,2);
            int tempo=Integer.parseInt(text);            
            CalcSaida calc=new CalcSaida();
            String f12 = Integer.toString((int) calc.calc(tempo));
            setValor.setText("R$"+" "+ f12+",00");
            
        try {
           
            
            con=new ConnectionFactory().getConnection();
                String getdatas=setDataS.getText();
                String gettempo=setTempo.getText();
                String getvalor=setValor.getText();

                String sql1="UPDATE tbl_movimentacao SET data_saida = '"+getdatas+"' , tempo='"+gettempo+"' , valor_pago='"+getvalor+"' WHERE id="+getId+"";
                
                stmt = con.prepareStatement(sql1);
                stmt.executeUpdate();
                con.close();
                
                
                
            con=new ConnectionFactory().getConnection(); 
                String sql2="insert into tbl_veiculoout (id,placa,modelo,data_entrada,data_saida,tempo,valor_pago)(select id,placa,modelo,data_entrada,data_saida,tempo,valor_pago from tbl_movimentacao where id= '"+getId+"')";
                String sql3="DELETE FROM tbl_movimentacao WHERE id = "+getId+"";
                st=con.createStatement();
                st.execute(sql2);
                st.execute(sql3);
                con.close();
                
                
          
                JOptionPane.showMessageDialog(null, "Sucesso");
                TelaPrincipal t = new TelaPrincipal();
                   t.setVisible(true);
                   this.hide();
                
        } catch (Exception e) {
           
        }
    }//GEN-LAST:event_btnSaidaActionPerformed

    private void setDataSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDataSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setDataSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaPrincipal t = new TelaPrincipal();
                   t.setVisible(true);
                   this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaida;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField setDataS;
    private javax.swing.JTextField setHoraEntrada;
    private javax.swing.JTextField setId;
    private javax.swing.JTextField setTempo;
    private javax.swing.JTextField setValor;
    // End of variables declaration//GEN-END:variables
}
