/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import factory.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import gui.Atualizar_carros;
import gui.Inserir_carros;
import gui.Saida_carros;
import java.sql.SQLException;
      
/**
 *
 * @author kaiov
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setResizable(false);
        try {
            Connection con;
            PreparedStatement stmt;
            
            con=new ConnectionFactory().getConnection();
                String sql = "select * from tbl_movimentacao";
                stmt = con.prepareStatement(sql);
                ResultSet rs = stmt.executeQuery();
                DefaultTableModel table = (DefaultTableModel)ViewCarros.getModel();
                table.setRowCount(0);
                table.setColumnCount(4);
                while (rs.next()) {
                table.addRow(new Object[]{rs.getString("id"),rs.getString("placa"),rs.getString("modelo"),rs.getString("data_entrada")});
                
            }
                rs.close();
                con.close();
            
                    
                }catch (Exception e) {}
        
    }
        
        
          
                
                
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Insertbtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        Exitbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ViewCarros = new javax.swing.JTable();
        setBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Janela Principal");

        Insertbtn.setText("Entrada");
        Insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertbtnActionPerformed(evt);
            }
        });

        Updatebtn.setText("Edição");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });

        Exitbtn.setText("Saída");
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });

        ViewCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Placa", "Modelo", "Data de Entrada"
            }
        ));
        ViewCarros.setToolTipText("");
        ViewCarros.setEnabled(false);
        ViewCarros.setMinimumSize(new java.awt.Dimension(300, 0));
        jScrollPane2.setViewportView(ViewCarros);
        if (ViewCarros.getColumnModel().getColumnCount() > 0) {
            ViewCarros.getColumnModel().getColumn(3).setMinWidth(150);
            ViewCarros.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        setBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veiculos Ativos", "Veiculos Inativos" }));
        setBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                setBoxItemStateChanged(evt);
            }
        });
        setBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Insertbtn)
                .addGap(80, 80, 80)
                .addComponent(Updatebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(Exitbtn)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(setBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insertbtn)
                    .addComponent(Updatebtn)
                    .addComponent(Exitbtn))
                .addGap(18, 18, 18)
                .addComponent(setBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        // TODO add your handling code here:
        Atualizar_carros t = new Atualizar_carros();
                   t.setVisible(true);
                   this.hide();
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void InsertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertbtnActionPerformed
        // TODO add your handling code here:
        Inserir_carros t = new Inserir_carros();
                   t.setVisible(true);
                   this.hide();
    }//GEN-LAST:event_InsertbtnActionPerformed

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        // TODO add your handling code here:
        Saida_carros t = new Saida_carros();
                   t.setVisible(true);
                   this.hide();
    }//GEN-LAST:event_ExitbtnActionPerformed

    private void setBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBoxActionPerformed
        // TODO add your handling code here:
    
            String op1="Veiculos Ativos";
        
        Object re=setBox.getSelectedItem();
        
    
        if (re==op1) {
            try {
            Connection con;
            PreparedStatement stmt;
            
            con=new ConnectionFactory().getConnection();
                String sql = "select * from tbl_movimentacao";
                stmt = con.prepareStatement(sql);
                ResultSet rs = stmt.executeQuery();
                DefaultTableModel table = (DefaultTableModel)ViewCarros.getModel();
                table.setRowCount(0);
                table.setColumnCount(4);
                while (rs.next()) {
                table.addRow(new Object[]{rs.getString("id"),rs.getString("placa"),rs.getString("modelo"),rs.getString("data_entrada")});
                
            }
                rs.close();
                con.close();
            
                    
                }catch (Exception e) {}}
    

  
    
    }//GEN-LAST:event_setBoxActionPerformed

    private void setBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_setBoxItemStateChanged
        // TODO add your handling code here
        Object re=setBox.getSelectedItem();
        String op2="Veiculos Inativos";
        if (re==op2) {
                try {
            Connection con;
            PreparedStatement stmt;
            
            con=new ConnectionFactory().getConnection();
                String sql = "select * from tbl_veiculoout";
                stmt = con.prepareStatement(sql);
                ResultSet rs = stmt.executeQuery();
                DefaultTableModel table = (DefaultTableModel)ViewCarros.getModel();
                table.setColumnCount(4);
                table.addColumn("Data Saída");
                table.addColumn("Tempo Estacionado");
                table.addColumn("Valor");
                table.setRowCount(0);
                while (rs.next()) {
                table.addRow(new Object[]{rs.getString("id"),rs.getString("placa"),rs.getString("modelo"),rs.getString("data_entrada"),rs.getString("data_saida"),rs.getString("tempo"),rs.getString("valor_pago")});
                
            }
                rs.close();
                con.close();
                
                
            
   } catch (Exception e) {}}
    }//GEN-LAST:event_setBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exitbtn;
    private javax.swing.JButton Insertbtn;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JTable ViewCarros;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> setBox;
    // End of variables declaration//GEN-END:variables
}
